"""One-shot generator: download Tunas signature icons and emit a Python
module (core/_tunas_icons.py) with each image embedded as a base64 data URI.

Run once (online) to (re)generate the bundled icons. After that the Tunas
template is fully self-contained — no network needed at insert time, so it
renders even behind firewalls that block raw.githubusercontent.com.
"""
import base64
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/KhatarMalayki/icontunas/master/ICON/"
ICONS = {
    "LOGO": "TUNASRENT-LOGO_fix.png",
    "INSTAGRAM": "Icon-01.png",
    "FACEBOOK": "Icon-02.png",
    "YOUTUBE": "Icon-03.png",
    "CALL": "Icon-04.png",
    "WHATSAPP": "Icon-05.png",
}

OUT = Path(__file__).parent / "core" / "_tunas_icons.py"


def fetch(name: str, fname: str) -> tuple[str, str]:
    url = BASE + fname
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=20) as resp:
        ctype = resp.headers.get("Content-Type", "image/png").split(";")[0].strip()
        data = resp.read()
    subtype = ctype.split("/", 1)[1] if "/" in ctype else "png"
    b64 = base64.b64encode(data).decode("ascii")
    print(f"  {name}: {len(data)} bytes -> {len(b64)} b64 chars ({subtype})")
    return f"data:image/{subtype};base64,{b64}", url


def main():
    print("Downloading Tunas icons...")
    entries = {}
    fallbacks = {}
    for name, fname in ICONS.items():
        data_uri, url = fetch(name, fname)
        entries[name] = data_uri
        fallbacks[name] = url

    lines = [
        '"""',
        "Auto-generated by _gen_tunas_icons.py. Do not edit by hand.",
        "",
        "Tunas signature icons embedded as base64 data URIs so the corporate",
        "signature template is fully self-contained (renders offline and behind",
        "firewalls that block raw.githubusercontent.com). Regenerate with:",
        "    python _gen_tunas_icons.py",
        '"""',
        "",
        "# Original source URLs (kept for reference / regeneration).",
        "SOURCE_URLS = {",
    ]
    for name, url in fallbacks.items():
        lines.append(f'    "{name}": "{url}",')
    lines.append("}")
    lines.append("")
    lines.append("ICONS = {")
    for name, data_uri in entries.items():
        lines.append(f'    "{name}": "{data_uri}",')
    lines.append("}")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    total = OUT.stat().st_size / 1024
    print(f"Wrote {OUT} ({total:.1f} KB)")


if __name__ == "__main__":
    main()
